# Generated by Django 2.2.10 on 2021-11-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poller', '0003_auto_20211108_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='voter_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
