# Generated by Django 2.2.10 on 2021-11-08 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poller', '0005_auto_20211108_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionanswer',
            name='voter_id',
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='voter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='poller.Voter'),
        ),
    ]
