# Generated by Django 2.2.10 on 2021-11-08 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poller', '0006_auto_20211108_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='voter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='voted_polls', to='poller.Voter'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
