# Generated by Django 2.2.10 on 2021-11-08 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poller', '0007_auto_20211108_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='voter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='votes', to='poller.Voter'),
        ),
    ]
