# Generated by Django 2.2.10 on 2021-11-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poller', '0008_auto_20211108_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='voter',
        ),
        migrations.AddField(
            model_name='poll',
            name='voter',
            field=models.ManyToManyField(blank=True, null=True, related_name='voted_polls', to='poller.Voter'),
        ),
    ]
