# Generated by Django 2.2.10 on 2021-11-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poller', '0009_auto_20211108_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='deleted',
            field=models.DateTimeField(null=True),
        ),
    ]
