# Generated by Django 2.2.10 on 2021-11-09 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poller', '0010_voter_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollquestion',
            name='poll',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='questions', to='poller.Poll'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='text',
            field=models.TextField(editable=False),
        ),
    ]
