# Generated by Django 2.2.10 on 2021-11-09 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poller', '0015_auto_20211109_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='text',
            field=models.TextField(),
        ),
    ]
